language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
sudo: false
before_script: cd TestingTravis
install: true
addons:
  sonarcloud:
    organization: dp-dev-github
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
