language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
sudo: false
before_script: cd TestingTravis
install: true
addons:
  sonarcloud:
    organization: "dp-dev-github"
script:
  - mvn clean install
mvn sonar:sonar -Dsonar.projectKey=dp-dev_testingCI -Dsonar.organization=dp-dev-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=SONAR_TOKEN
